### ISSUE TITLE
PHP thread title doesn't load correctly

### ISSUE THREAD

**Issue by MasterOdin** [2fast2fourier/something.apk#7]
Never changes from "Loading...". Probably has to do with the special characters in the title.

[ <?PHP questions that don\\'t need their own thread ?>]( http://forums.somethingawful.com/showthread.php?threadid=2802621)

Might want to check other oddly named programming threads.

**Comment by MasterOdin** [comment]
Github doesn't fully like it either in plaintext.

``` <?PHP questions that don\\'t need their own thread ?>```

**Comment by Sereri** [comment]
It works in Awful, maybe look what the differences are. Also consider updating jSoup

**Comment by MasterOdin** [comment]
Tested against ```jQuery("#megathread").addClass("questions").show();```, ```<?PHP questions that don\\'t need their own thread ?>```, and ```Grad school & academia: Dammit, who's been drinking my thesis whiskey``` and all display fine. Probably not any other truly wacky cases that these titles don't cover.
