### ISSUE TITLE
Dropdown Menus should not be OS colored

### ISSUE THREAD

**Issue by MasterOdin** [2fast2fourier/something.apk#9]
KitKat colors dropdowns in black while Lollipop colors it white causing:

![example](http://i.imgur.com/9W1y3Gh.png)

Should come up with more consistent coloring regardless of OS version (or make the icon colors OS dependent).

**Comment by 2fast2fourier** [comment]
The best option is probably to make the background consistent. It is possible to make API21-specific images, but there have been weird cases where one manufacturer will decide to change that background color to something else and then we are back to square one.
